Set Theme "GruvboxDark"
Require "sper"
Output demo.gif

Set FontFamily "JetBrainsMono Nerd Font Mono,JetBrainsMono NFM"
Set FontSize 16
Set Width 1280
Set Height 720

Env SPER_LICENSE_DIR "/home/myxi/Documents/licenses"

Type "cat $SPER_LICENSE_DIR/MIT"
Sleep 2s
Enter
Sleep 3s

Type "sper MIT"
Sleep 2s
Enter
Sleep 3s

Type "2024"
Sleep 2s
Enter
Sleep 3s

Type "myxi"
Sleep 2s
Enter
Sleep 3s

Type "LICENSE"
Sleep 2s
Enter
Sleep 3s

Type "cat LICENSE"
Sleep 2s
Enter
Sleep 5s

